### ISSUE TITLE
Utilise Cortex Analyzers?

### ISSUE THREAD

**Issue by geekscrapy** [countercept/snake#4]
Thoughts on implementing Cortex Analyzers (https://github.com/TheHive-Project/Cortex-Analyzers) alongside existing Snake Scales?

Potentially a quick and easy way to integrate more analysers into the project. They are pretty actively worked on.

**Comment by alexkornitzer** [comment]
That is an interesting idea, I guess it depends on what parts would be useful to port across. In theory, I would probably argue that it is quicker to convert the wanted features into scales as their development overhead should be fairly low. I also think that we can improve upon them due to the functionality that Snake exposes.

I understand the reasoning behind the quick win aspect, but I am unsure to the overhead required to incorporate this layer into the backend. When I have some time I will look into cherry picking the ones that I think are most useful, but feel free to beat me to it!
